development:
  adapter: postgresql
  encoding: unicode
  database: pykhub
  host: 192.168.0.119
  pool: 5
  username: devrp
  password: developer

production:
  adapter: postgresql
  encoding: unicode
  database: pykhub
  pool: 5
  username: ritvvijparrikh
  password: